import { CartProvider } from "./context/CartContext";
import dynamic from "next/dynamic";
import { Geist, Geist_Mono } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

// Use ClientOnlyWrapper for client-only components (handles ssr: false internally)
const ClientOnlyWrapper = dynamic(
  () => import("./Components/ClientOnlyWrapper"),
  {
    loading: () => null,
  }
);

// Navbar can be server-rendered (above fold)
const NavBarScrollEffect = dynamic(
  () => import("./Components/Navbar/NavBarScrollEffect")
);

// Footer is below fold - lazy load for mobile
const Footer = dynamic(
  () => import("./Components/Footer/Footer").then((mod) => ({ default: mod.Footer })),
  {
    loading: () => <div className="min-h-[200px]" />,
  }
);

// Optimize font loading for better LCP
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
  adjustFontFallback: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartProvider>
      <html lang="en">
        <head>
          {/* Resource hints - removed unused preconnect for cdn.shopify.com */}
          <link rel="dns-prefetch" href="https://fonts.googleapis.com" />
          {/* Critical CSS inline for above-the-fold content - defer non-critical */}
          <style dangerouslySetInnerHTML={{
            __html: `
              /* Critical above-the-fold styles */
              body{margin:0;font-family:var(--font-geist-sans),system-ui,-apple-system,sans-serif}
              .scrollbar-hide{-ms-overflow-style:none;scrollbar-width:none}
              .scrollbar-hide::-webkit-scrollbar{display:none}
            `
          }} />
          {/* Note: CSS is automatically handled by Next.js - no need to manually preload */}
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <NavBarScrollEffect />
          {children}
          {/* Client-only components loaded after page is interactive */}
          <ClientOnlyWrapper />
          <Footer />
          <SpeedInsights />
        </body>
      </html>
    </CartProvider>
  );
}
